<?php
/**
 * @file
 * Main module file for Digital Strategy module.
 */


/**
 * Implements hook_menu().
 */
function digital_strategy_menu() {
  $items = array();

  // Loops through the digital strategy type variables to create menu callbacks for each type	
	foreach (variable_get('digital_strategy_types', array("xml", "json", "jsonp", "html")) as $type) {
		// create callback menu item for everything except html
		if ($type != 'html') {
			$items['digitalstrategy.' . $type] = array(
				'access arguments' => array('access content'),
				'page callback' => '_digital_strategy_themeless',
				'page arguments' => array($type),
				'title' => $type,
				'type' => MENU_CALLBACK, 
			);
		}
	} // end foreach
	
	return $items;
}

// Page callback function for digital strategy type variables
function _digital_strategy_themeless($type = '') {
	// get the node based on the path
  // we know the path because we created it
  $alias = "digitalstrategy/" . $type;
  $path = drupal_lookup_path("source", $alias);
  $node = menu_get_object("node", 1, $path);
  
  // set correct content type header
  $content_type = 'application/json';
  if ($type == 'xml') {
    $content_type = 'text/xml';
  }
  drupal_set_header("Content-Type: " . $content_type . "; charset=utf-8");

  // output the body content only without the theme layer
  echo $node->body;
}